apiVersion: v1
kind: Service
metadata:
  name: nats-client
  labels:
    component: nats
    usage: client
spec:
  selector:
    component: nats
  type: ClusterIP
  ports:
  - name: client
    port: 4222
