apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: elasticsearch-data
  labels:
    app: elasticsearch
    role: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
      role: data
  template:
    metadata:
      labels:
        app: elasticsearch
        role: data
    spec:
      serviceAccount: elasticsearch
      containers:
        - name: es-data
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          image: quay.io/pires/docker-elasticsearch-kubernetes:1.7.1-4
          env:
            - name: KUBERNETES_CA_CERTIFICATE_FILE
              value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: "CLUSTER_NAME"
              value: "cota-k8s"
            - name: NODE_MASTER
              value: "false"
            - name: HTTP_ENABLE
              value: "false"
          ports:
            - containerPort: 9300
              name: transport
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: elasticsearch
