apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: account
    owner: tonyhhyip
    stage: rc
  name: account-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account
      owner: tonyhhyip
      stage: rc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: account
        owner: tonyhhyip
        stage: rc
    spec:
      containers:
      - image: ysitd/cloud-account-sidecar:1.7.2
        imagePullPolicy: IfNotPresent
        name: renderer
        env:
          - name: NODE_ENV
            value: production
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        ports:
          - containerPort: 8080
            protocol: TCP
            name: sidecar
      - image: ysitd/cloud-account:1.7.2
        imagePullPolicy: IfNotPresent
        name: account-manager
        env:
        - name: GIN_MODE
          value: release
        - name: STATIC_ADDRESS
          value: https://assets.ysitd.cloud
        - name: SIDECAR_URL
          value: http://localhost:8080
        - name: LISTEN_PORT
          value: "80"
        - name: PORT
          value: "80"
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              key: dbUrl
              name: account-db
        - name: REDIS_ADDRESS
          value: account-redis.lab:6379
        - name: REDIS_DB
          value: "1"
        - name: SESSION_NAME
          value: ysitd
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        - containerPort: 50051
          protocol: TCP
          name: grpc
        resources:
          limits:
            cpu: 100m
            memory: 8Mi
          requests:
            cpu: 10m
            memory: 4Mi
