apiVersion: v1
kind: Service
metadata:
  labels:
    app: account
    owner: tonyhhyip
    stage: rc
  name: account-manager
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: sidecar
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: account
    owner: tonyhhyip
  type: ClusterIP
