apiVersion: v1
kind: Service
metadata:
  name: rethinkdb
  labels:
    app: rethinkdb
    owner: public
spec:
  clusterIP: None
  ports:
    - port: 29015
      targetPort: 29015
  selector:
    app: rethinkdb
    owner: public
