apiVersion: v1
kind: Service
metadata:
  name: rethinkdb-proxy
  labels:
    app: rethinkdb-proxy
    owner: public
spec:
  type: ClusterIP
  ports:
    - name: admin
      port: 8080
      targetPort: 8080
    - name: service
      port: 28015
      targetPort: 28015
  selector:
    app: rethinkdb-proxy
    owner: public
