kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: rethinkdb-proxy
  labels:
    app: rethinkdb-proxy
    owner: public
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rethinkdb-proxy
      owner: public
  template:
    metadata:
      name: rethinkdb-proxy
      labels:
        app: rethinkdb-proxy
        owner: public
    spec:
      serviceAccountName: rethinkdb
      containers:
        - name: rethinkdb-proxy
          image: codylundquist/helm-rethinkdb-cluster:0.1.0
          ports:
            - name: cluster
              containerPort: 29015
            - name: service
              containerPort: 28015
            - name: admin
              containerPort: 8080
          args:
            - --bind
            - all
          volumeMounts:
            - name: secrets
              mountPath: /secrets
          env:
            - name: PROXY
              value: "true"
            - name: RETHINK_CLUSTER_SERVICE
              value: rethinkdb
            - name: RETHINKDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rethinkdb
                  key: rethinkdb-password
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      volumes:
        - name: secrets
          projected:
            sources:
            - secret:
                name: rethinkdb
