apiVersion: v1
kind: Service
metadata:
  labels:
    app: rethinkdb-cluster
    owner: public
  name: rethinkdb-cluster
spec:
  ports:
  - name: admin
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: service
    port: 28015
    protocol: TCP
    targetPort: 28015
  selector:
    app: account
    owner: tonyhhyip
  type: ClusterIP
