apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rethinkdb
  labels:
    app: rethinkdb
    owner: public
spec:
  serviceName: rethinkdb
  replicas: 3
  template:
    metadata:
      name: rethinkdb
      labels:
        app: rethinkdb
        owner: public
    spec:
      serviceAccountName: rethinkdb
      containers:
        - name: rethinkdb
          image: codylundquist/helm-rethinkdb-cluster:0.1.0
          ports:
            - name: cluster
              containerPort: 29015
          args:
            - "--directory"
            - "/data/db"
            - "--bind"
            - "all"
            - "--no-http-admin"
            - "--cache-size"
            - "100"
          volumeMounts:
            - name: "datadir"
              mountPath: "/data"
          env:
            - name: RETHINK_CLUSTER_SERVICE
              value: rethinkdb
            - name: RETHINKDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rethinkdb
                  key: rethinkdb-password
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            exec:
              command:
                - /rethinkdb-probe
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /rethinkdb-probe
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          volume.beta.kubernetes.io/storage-class: share
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "2Gi"
