apiVersion: v1
kind: Service
metadata:
  labels:
    owner: tonyhhyip
    app: app-controller
  name: app-controller
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    owner: tonyhhyip
    app: app-controller
  type: ClusterIP
