apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: rethinkdb
  labels:
    app: rethinkdb
    owner: tonyhhyip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rethinkdb
      owner: tonyhhyip
  template:
    metadata:
      labels:
        app: rethinkdb
        owner: tonyhhyip
    spec:
      containers:
        - name: rethinkdb
          image: rethinkdb:2.3
          volumeMounts:
            - mountPath: /data
              name: data
          ports:
            - containerPort: 8080
            - containerPort: 28015
            - containerPort: 29015
      volumes:
        - name: data
          azureFile:
            secretName: lab-files
            shareName: rethink
            readOnly: false
