---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-storage
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
