apiVersion: v1
name: traefik
version: 1.3.0
appVersion: 1.2.1
description: A Traefik based Kubernetes ingress controller with Let's Encrypt support
keywords:
- traefik
- ingress
- acme
- letsencrypt
home: http://traefik.io/
sources:
- https://github.com/containous/traefik
- https://github.com/krancour/charts/tree/master/traefik
- https://github.com/tonyhhyip/cota-k8s-deployment
maintainers:
- name: Kent Rancourt
  email: kent.rancourt@microsoft.com
- name: Tony Yip
  email: tony@opensource.hk
engine: gotpl
icon: http://traefik.io/traefik.logo.png
