apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-ingress
  labels:
    app: traefik
    usage: ingress-controller
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "INFO"
    defaultEntryPoints = ["http"]
    [accessLog]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
    [kubernetes]
    [web]
    address = ":8080"
