apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress
  labels:
    app: traefik
    usage: ingress-controller
spec:
  type: LoadBalancer
  selector:
    app: traefik
    usage: ingress-controller
  ports:
  - port: 80
    name: http
