apiVersion: v1
kind: Service
metadata:
  annotations:
    usage: internal
  name: traefik-web
  labels:
    app: traefik
    usage: monitor
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: traefik
    usage: ingress-controller
  type: ClusterIP
