kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-controller
  namespace: core-apps
rules:
- apiGroups: [""]
  resources:
    - endpoints
  verbs: ["get"]
- apiGroups: [""]
  resources:
    - secrets
    - services
  verbs: ["get", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources:
    - deployments
  verbs: ["get", "create", "update", "patch", "delete"]
- apiGroups: ["extensions"]
  resources:
    - ingresses
  verbs: ["get", "create", "update", "patch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-controller
  namespace: core-apps
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-controller
  namespace: core-apps
subjects:
- kind: ServiceAccount
  name: app-controller
  namespace: app-controller
roleRef:
  kind: Role
  name: app-controller
  apiGroup: rbac.authorization.k8s.io
