kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-controller
rules:
- apiGroups: [""]
  resources:
    - secrets
    - services
  verbs: ["get", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources:
    - deployments
  verbs: ["get", "create", "update", "patch", "delete"]
- apiGroups: ["extensions"]
  resources:
    - ingresses
  verbs: ["get", "create", "update", "patch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-controller
  namespace: lab
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-controller
subjects:
- kind: ServiceAccount
  name: app-controller
  namespace: app-controller
roleRef:
  kind: ClusterRole
  name: app-controller
  apiGroup: rbac.authorization.k8s.io
