apiVersion: v1
kind: Service
metadata:
  name: kube-registry-expose
  namespace: kube-system
  labels:
    k8s-app: kube-registry
    version: v0
    kubernetes.io/cluster-service: "true"
spec:
  type: NodePort
  selector:
    k8s-app: kube-registry
  ports:
    - name: registry
      port: 5000
      nodePort: 30000
      protocol: TCP
