apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  labels:
    role: master
    app: elasticsearch
spec:
  selector:
    role: master
    app: elasticsearch
  ports:
  - name: transport
    port: 9300
    protocol: TCP
