kind: ServiceAccount
apiVersion: v1
metadata:
  name: elasticsearch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: elasticsearch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoints-getter
subjects:
  - kind: ServiceAccount
    namespace: elasticsearch
    name: elasticsearch
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: endpoints-getter
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
