apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  name: sessions
spec:
  size: 3
  version: 3.3.1
  pod:
    etcdEnv:
    - name: ETCD_AUTO_COMPACTION_RETENTION
      value: "1"
