apiVersion: v1
kind: Service
metadata:
  name: etcd-client
  labels:
    usage: kv
    component: etcd
    owner: public
spec:
  ports:
    - port: 2379
      name: etcd-client
  type: ClusterIP
  selector:
    component: etcd
