apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    usage: discovery
    component: etcd
    owner: public
spec:
  ports:
    - port: 2380
      name: etcd-server
    - port: 2379
      name: etcd-client
  type: ClusterIP
  clusterIP: None
  selector:
    component: etcd
