name: minio

image:
  repository: minio/minio
  tag: "RELEASE.2017-06-13T19-01-01Z"
  pullPolicy: Always

replicaCount: 1

resource:
  requests:
    cpu: 200m
    memory: 20Mi
  limits:
    cpu: 300m
    memory: 50Mi

service:
  externalPort: 9000
  internalPort: 80
  type: ClusterIP

ingress:
  enabled: false

secretName: storage-key
