apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdBackup
metadata:
  name: general
spec:
  etcdEndpoints: ["http://general:2379"]
  storageType: S3
  s3:
    path: storage/general
    awsSecret: backup
    endpoint: http://etcd:9000
