apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  name: general
spec:
  size: 3
  version: 3.2.18
  pod:
    etcdEnv:
      - name: ETCD_AUTO_COMPACTION_RETENTION
        value: "1"
