kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: cota-wordpress
  labels:
    owner: cota
    app: wordpress
spec:
  template:
    metadata:
      labels:
        owner: cota
        app: wordpress
    spec:
      imagePullSecrets:
        - name: azr
      volumes:
        - name: upload
          azureFile:
            secretName: cotablob-file
            shareName: cota-wordpress
            readOnly: false
      containers:
        - name: nginx
          image: hkcota.azurecr.io/cota/wordpress:2.2.0-nginx
          livenessProbe:
            tcpSocket:
              port: http
            timeoutSeconds: 1
          volumeMounts:
            - name: upload
              mountPath: /var/www/html/wp-content/uploads
          ports:
            - containerPort: 80
              name: http
        - name: fpm
          image: hkcota.azurecr.io/cota/wordpress:2.2.0-fpm
          livenessProbe:
            tcpSocket:
              port: fpm
            timeoutSeconds: 1
          ports:
            - containerPort: 9000
              name: fpm
          volumeMounts:
            - name: upload
              mountPath: /var/www/html/wp-content/uploads
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: cota-wp-mysql
                  key: dbHost
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cota-wp-mysql
                  key: dbName
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: cota-wp-mysql
                  key: dbUser
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cota-wp-mysql
                  key: dbPassword
