apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cota-wordpress
  labels:
    owner: cota
    app: wordpress
spec:
  rules:
  - host: cota.hk
    http:
      paths:
      - backend:
          serviceName: cota-wordpress
          servicePort: 80
        path: /
      - backend:
          serviceName: cota-nginx
          servicePort: 80
        path: /wp-content/uploads
      - backend:
          serviceName: hkcota-minio
          servicePort: 9000
        path: /archive
  - host: www.cota.hk
    http:
      paths:
      - backend:
          serviceName: cota-wordpress
          servicePort: 80
        path: /
      - backend:
          serviceName: cota-nginx
          servicePort: 80
        path: /wp-content/uploads
      - backend:
          serviceName: hkcota-minio
          servicePort: 9000
        path: /archive
