apiVersion: v1
kind: Service
metadata:
  annotations:
    usage: internal
  labels:
    app: traffic-traefik
    chart: traefik-1.3.0
    heritage: Tiller
    release: traffic
  name: traefik-web
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: traffic-traefik
  type: ClusterIP
