kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    usage: monitor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: share
