kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: graylog
  labels:
    app: graylog
    usage: monitor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: share
