apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
  labels:
    app: minio
    account: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minio
      account: default
  template:
    metadata:
      labels:
        app: minio
        account: default
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2018-04-04T05-20-54Z
          commands:
          args:
            - gateway
            - azure
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: storage
                  key: ACCESS_KEY_ID
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: storage
                  key: SECRET_ACCESS_KEY
          ports:
            - containerPort: 9000
