apiVersion: v1
kind: Service
metadata:
  name: storage
  labels:
    app: minio
    account: default
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
    account: default
  type: ClusterIP
